[phases.setup]
nixPkgs = ['nodejs-20_x', 'yarn']
aptPkgs = ['git']
providers = ['node']

[phases.install]
cmds = ['yarn']

[phases.build]
cmds = ['yarn build:admin:deployment']

[start]
cmd = 'yarn serve -s dist/admin -l 7001'