[phases.setup]
nixPkgs = ['nodejs', 'yarn']
workdir = "ecomm"

[phases.install]
cmds = ['yarn install']

[phases.build]
cmds = ['yarn build:admin:deployment']

[start]
cmd = 'yarn serve -s dist/admin -l 7001'